// This file was auto-generated by Fern from our API Definition.

package api

import (
	fmt "fmt"
)

type FindPetsByStatusRequest struct {
	// Status values that need to be considered for filter
	Status *FindPetsByStatusRequestStatus `json:"-"`
}

type FindPetsByTagsRequest struct {
	// Tags to filter by
	Tags []*string `json:"-"`
}

type FindPetsByStatusRequestStatus string

const (
	FindPetsByStatusRequestStatusAvailable FindPetsByStatusRequestStatus = "available"
	FindPetsByStatusRequestStatusPending   FindPetsByStatusRequestStatus = "pending"
	FindPetsByStatusRequestStatusSold      FindPetsByStatusRequestStatus = "sold"
)

func NewFindPetsByStatusRequestStatusFromString(s string) (FindPetsByStatusRequestStatus, error) {
	switch s {
	case "available":
		return FindPetsByStatusRequestStatusAvailable, nil
	case "pending":
		return FindPetsByStatusRequestStatusPending, nil
	case "sold":
		return FindPetsByStatusRequestStatusSold, nil
	}
	var t FindPetsByStatusRequestStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (f FindPetsByStatusRequestStatus) Ptr() *FindPetsByStatusRequestStatus {
	return &f
}

type UpdatePetWithFormRequest struct {
	// Name of pet that needs to be updated
	Name *string `json:"-"`
	// Status of pet that needs to be updated
	Status *string `json:"-"`
}
